# Generated by Django 2.2.6 on 2019-10-26 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orpanageneed',
            name='id_type',
        ),
        migrations.AddField(
            model_name='orpanageneed',
            name='id_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='needs.NeedType'),
            preserve_default=False,
        ),
    ]
