# Generated by Django 2.2.6 on 2019-10-26 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20191026_1311'),
        ('needs', '0002_auto_20191026_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Animal')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='needs.NeedType')),
            ],
        ),
    ]
