# Generated by Django 2.2.6 on 2019-10-26 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0003_animalneed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalneed',
            name='id_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.Animal'),
        ),
    ]
